- hosts: localhost
  tasks:
  - pip:
      name: "boto3"
  - ec2_instance:
      region: us-east-1
      image_id: ami-04d29b6f966df1537
      instance_type: t2.micro
      vpc_subnet_id: subnet-6884ed66
      security_group: sg-0be57591b8879d2ff
      key_name: arthos
      name: ansi
      state: present
      aws_access_key: AK**************AMV
      aws_secret_key: m7Egr0hw*******************RyJtj+O
